### ISSUE TITLE
migrate to null-safety

### ISSUE THREAD

**Issue by ghost** [virskor/DiscuzQ#167]
Hi @virskor ,

Hope you are all well !

I wanted to try your project but I was wondering if you could migrate it to null safety ?

List of missing and not migrated packages:
```yaml
  flutter_swiper:
    git: https://github.com/Arkangel12/flutter_swiper
  md2_tab_indicator:
    git: https://github.com/westdabestdb/md2_tab_indicator
  flutter_absolute_path:
    git:
      url: https://github.com/ValeriusGC/flutter_absolute_path
      ref: topic/null_safety
```

Thanks for any insights or inputs on that.

Cheers,
Luc
